name: DVC & CML Workflow

on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup
        run: |
          pip install -r requirements.txt
      - name: Pull Data
        continue-on-error: true
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          dvc pull --force
      - name: Run DVC pipeline
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          dvc repro
      - name: Share changes
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          dvc push
      - name: Create a P.R. with CML 
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml pr --rebase "dvc.lock" "params.yaml" "outs/*.json" "outs/eval"  "outs/train_metrics"
      - name: Setup tmate debug session
        # if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
        if: ${{ github.event.inputs.debug_enabled }}
        uses: mxschmitt/action-tmate@v3
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: CML Report
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          set -x
          echo "## Metrics & Params" >> report.md
          dvc exp diff main --show-md >> report.md
                  
          echo "## Plots" >> report.md
          echo "### Eval Loss" >> report.md
          dvc plots diff \
            --target outs/train_metrics/scalars/eval/loss.tsv --show-vega main > vega.json
          vl2png vega.json -s 1.5 > plot_loss.png
          echo '![](./plot_loss.png "eval loss")'  >> report.md
          echo "### Eval Accuracy" >> report.md
          dvc plots diff \
            --target outs/train_metrics/scalars/eval/accuracy.tsv --show-vega main > vega.json
          vl2png vega.json -s 1.5 > plot_acc.png
          echo '![](./plot_acc.png "eval accuracy")'  >> report.md
          echo "### Confusion Matrix" >> report.md
          dvc plots diff \
            --target outs/eval/plots/confusion_matrix.json --show-vega main > vega.json
          vl2png vega.json -s 1.5 > plot_cm.png
          echo '![](./plot_cm.png "confusion matrix")'  >> report.md
          cml comment create --target=pr report.md
          set +x